services:
  - type: web
    name: craftix-web
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
